import Conexion

#crear tabla tienda
Conexion.cursor.execute(
                """
                CREATE TABLE TIENDA( 
                Rank INT,
                Name VARCHAR(150),
                Platform VARCHAR(15),
                Year INT,
                Genre VARCHAR(20),
                Publisher VARCHAR(40),
                NA_Sales FLOAT,
                EU_Sales FLOAT,
                JP_Sales FLOAT,
                Other_Sales FLOAT,
                Global_Sales FLOAT
                )
                """
)

#crear tabla biblioteca
Conexion.cursor.execute(
                """
                CREATE TABLE BIBLIOTECA( 
                Id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                Rank INT,
                Name VARCHAR(150),
                Platform VARCHAR(15),
                Year INT,   
                Genre VARCHAR(20),
                Publisher VARCHAR(40),
                Rating INT 
                )
                """
)